feat: deno 1.31.1 compat
denoland/deno_bindgen pull request #117
Opened 2023-03-05 12:51 UTC by zifeo

2023-03-05 13:59 UTC, zifeo commented
@littledivy please review

2023-03-09 18:21 UTC, lino-levan requested changes
Outside of the one nitpick, this looks good to me.

2023-03-09 18:21 UTC, lino-levan commented on codegen.ts
> +  solaris: uri + "lib${name}.so",
This seems unrelated to the PR. Could you revert this and split this off into another PR?

2023-03-09 18:30 UTC, lino-levan commented on codegen.ts
> +  solaris: uri + "lib${name}.so",
Maybe there was a change to `/x/plug`. This seems to me to not be super future-proof. I think we should be using [name guessing](https://github.com/denosaurs/plug#example-using-automatic-binary-name-guessing) here.

2023-03-15 12:41 UTC, zifeo commented
Closed in favour of #118

2023-03-15 12:41 UTC, closed without merging